### ISSUE TITLE
Dev content review - 3

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-microprofile-istio-retry-fallback#8]
- [x] after force replace the yaml, the system pod name will be regenerated, so need to ask readers to run `kubectl get pods` again to get the new `[system-pod-name]`
- [x] at "Turning off MicroProfile Fault Tolerance" section, the first hotspot `ConfigMap` under the Update command should highlist the whole section instead of one line
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-config
data:
  MP_Fault_Tolerance_NonFallback_Enabled: "false" 
```
